
^CivBuilding:
	Defaults:
		Offset: 0, 0, 5
		UseTilesetCode: false
	idle:
		ShadowStart: 3
	damaged-idle:
		Start: 1
		ShadowStart: 4
	ruins:
		Start: 2
		ShadowStart: 5




^Props:
	Defaults:
		Offset: 0, 0, 30
		UseTilesetCode: false
	idle:
		ShadowStart: 2
	damaged-idle:
		Start: 1
		ShadowStart: 3


^bridge:
	Defaults:
		ZOffset: -1c511
		UseTilesetExtension: true
		Start: 1
		ZRamp: 1
		Offset: 0, 0, 0.5

^Rock:
	idle:
		ShadowStart: 1
		Offset: 0, 0, 5
		UseTilesetExtension: true

^Drill:
	Defaults:
		UseTilesetExtension: true
		Offset: -1, -30, 16
	idle:
		ShadowStart: 11
	active:
		Start: 1
		Length: 10
		ShadowStart: 12
		Tick: 160

^WithMachineGunMuzzle:
	muzzle0: mgun-n
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle1: mgun-nw
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle2: mgun-w
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle3: mgun-sw
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle4: mgun-s
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle5: mgun-se
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle6: mgun-e
		Length: *
		Offset: 0, 0
		UseTilesetCode: false
	muzzle7: mgun-ne
		Length: *
		Offset: 0, 0
		UseTilesetCode: false

^WithCannonMuzzle:
	muzzle: gunfire
		Length: *
	muzzle-2: vtmuzzle
		Length: *

^WithFlakMuzzle:
	muzzle: gunfire
		Length: *
		Offset: 0,0
		UseTilesetCode: false

^WithFlakMuzzle2:
	muzzle-2: gunfire
		Length: *
		Offset: 0,0
		UseTilesetCode: false

^onfire:
	fire: fire04
		Length: *
		BlendMode: Additive
		ZOffset: 512
		Tick: 100
	spark: spark
		Length: *
		BlendMode: Additive

^CommonVehicale:
	Inherits: ^onfire
	Defaults: 
		Offset: 0,0,0
		UseTilesetCode: false
	paradrop:
		Facings: -32
	idle: 
		Facings: -32
		ShadowStart: 32
	stand: 
		Facings: -32
		ShadowStart: 32
	run: 
		Facings: -32
		ShadowStart: 32

^BasicInfantry:
	Defaults:
		Offset: 0, 0, 16
	stand:
		Facings: 8
	run:
		Start: 8
		Length: 12
		Facings: 8
		Tick: 100
	shoot:
		Start: 104
		Length: 9
		Facings: 8
		Tick: 80
	idle1:
		Start: 176
		Length: 19
	idle2:
		Start: 195
		Length: 14
	die1:
		Start: 8
		Length: 6
		Facings: 8
		Tick: 80
	die2:
		Start: 8
		Length: 6
		Facings: 8
		Tick: 80
	die3:
		Start: 8
		Length: 5
		Facings: 8
		Tick: 80
	paradrop:
	cheer:
	liedown:
		Length: 7
		Facings: 8
		Tick: 80
	standup:
		Start: 56
		Length: 4
		Facings: 8
	prone-stand:
		Facings: 8
	prone-run:
		Start: 8
		Length: 12
		Facings: 8
		Tick: 100
	prone-shoot:
		Start: 104
		Length: 9
		Facings: 8
		Tick: 80
	icon: xxicon

^Tree:
	idle:
		ShadowStart: 2
		UseTilesetExtension: true
		Offset: 0, 0, 16
	burnt:
		Start: 1
		ShadowStart: 3
		UseTilesetExtension: true
		Offset: 0, 0, 16
	fire: fire01
		Length: *
		BlendMode: Additive
		Offset: 0, -22, 50