^CommonTank:
	Defaults: 
		Offset: 0,0,0
		UseTilesetCode: false
	idle: 
		Facings: -32
		ShadowStart: 32
	stand: 
		Facings: -32
		ShadowStart: 32
	run: 
		Facings: -32
		ShadowStart: 32

^BasicInfantry:
	Defaults:
		Offset: 0, 0, 16
	stand:
		Facings: 8
	run:
		Start: 8
		Length: 12
		Facings: 8
		Tick: 100
	shoot:
		Start: 104
		Length: 9
		Facings: 8
		Tick: 80
	idle1:
		Start: 176
		Length: 19
	idle2:
		Start: 195
		Length: 14
	die1:
		Start: 8
		Length: 6
		Facings: 8
		Tick: 80
	die2:
		Start: 8
		Length: 6
		Facings: 8
		Tick: 80
	die3:
		Start: 8
		Length: 5
		Facings: 8
		Tick: 80
	paradrop:
	cheer:
	liedown:
		Length: 7
		Facings: 8
		Tick: 80
	standup:
		Start: 56
		Length: 4
		Facings: 8
	prone-stand:
		Facings: 8
	prone-run:
		Start: 8
		Length: 12
		Facings: 8
		Tick: 100
	prone-shoot:
		Start: 104
		Length: 9
		Facings: 8
		Tick: 80
	icon: xxicon


^Tree:
	idle:
		ShadowStart: 2
		UseTilesetExtension: true
		Offset: 0, 0, 16
	burnt:
		Start: 1
		ShadowStart: 3
		UseTilesetExtension: true
		Offset: 0, 0, 16
	fire: fire01
		Length: *
		BlendMode: Additive
		Offset: 0, -22, 50