###
# ^SpiritVehicle
# ^TurretedVehicle
# ^AtkFrontalVehicle
# ^CommonAircraft
###
^ExistsInWorld:
	AppearsOnRadar:
	UpdatesPlayerStatistics:
	CombatDebugOverlay:
	RenderDebugState:
	DrawLineToTarget:
	GivesExperience:
	ScriptTriggers:
	ConditionManager:
	Huntable:

^SpiritVehicle:
	Inherits@1: ^ExistsInWorld
	Inherits@2: ^GainsExperience
	Inherits@3: ^IronCurtainable
	Inherits@4: ^ChronoDisable
	Inherits@5: ^CrateStatModifiers
	Inherits@6: ^ParachutableVehicle
	OwnerLostAction:
		Action: Kill
		DeathTypes: BulletDeath
	Mobile:
		Voice: Move
		TurnSpeed: 5
		Locomotor: wheeled
	SelectionDecorations:
		Palette: pips
	Selectable:
		Bounds: 32,32
	Targetable:
		TargetTypes: Ground, Vehicle, DetonateAttack
	Targetable@REPAIR:
		RequiresCondition: damaged
		TargetTypes: Repair
	GrantConditionOnDamageState@DAMAGED:
		Condition: damaged
		ValidDamageStates: Light, Medium, Heavy, Critical
	Repairable:
		Voice: Move
		RepairActors: gadept, nadept, caoutp, repairdepot
	Passenger:
		Voice: Move
		CargoType: Vehicle
		Weight: 3
	HiddenUnderFog:
	WithTextControlGroupDecoration:
	ActorLostNotification:
	ProximityCaptor:
		Types: Vehicle
	Guard:
		Voice: Attack
	Guardable:
	BodyOrientation:
		QuantizedFacings: 0
		CameraPitch: 85
		UseClassicPerspectiveFudge: false
	Explodes:
		Weapon: SmallExplosion
		EmptyWeapon: SmallExplosion
	# RenderVoxels:
	# 	Scale: 11.7
	# 	LightYaw: 800
	# 	LightPitch: 150
	# 	LightAmbientColor: -0.5,-0.5,-0.5
	# 	LightDiffuseColor: 1.4,1.4,1.4
	MustBeDestroyed:
	MapEditorData:
		Categories: Vehicle
	Voiced:
		VoiceSet: VehicleVoice
	WithFacingSpriteBody:
	RenderSprites:
	# GrantConditionOnMovement:
	# 	Condition: moving
	AmbientSound@tank:
		SoundFiles: tank_rev0.wav
		Delay: 0
		Interval: 0
		RequiresCondition: trackmoving
	AmbientSound@track:
		SoundFiles: tank_tracks.wav
		Delay: 0
		Interval: 0
		RequiresCondition: trackmoving
	AmbientSound@wheel:
		SoundFiles: jeep_rev.wav
		Delay: 0
		Interval: 0
		RequiresCondition: wheelmoving
	Targetable@materials:
		TargetTypes: Metel


^TurretedVehicle:
	Inherits: ^SpiritVehicle
	WithSpriteTurret:
	AttackTurreted:
		Voice: Attack
	Turreted:
		TurnSpeed: 20
	AutoTarget:
	HitShape:

^AtkFrontalVehicle:
	Inherits: ^SpiritVehicle
	AttackFrontal:
		Voice: Attack
		AutoTarget:
	HitShape:


^DefenceBuilding:
	Inherits: ^SupportBuilding
	Targetable:
		TargetTypes: Ground, C4, DetonateAttack, Structure, Defense

^Plane:
	Inherits@2: ^GainsExperience
	Inherits@1: ^ExistsInWorld
	OwnerLostAction:
		Action: Kill
		DeathTypes: BulletDeath
	Targetable@airborne:
		TargetTypes: Air
		RequiresCondition: airborne
	SelectionDecorations:
		Palette: pips
	Selectable:
	ActorLostNotification:
	Interactable:
	Aircraft:
		Voice: Move
		AirborneCondition: airborne
		CanHover: True
		VTOL: true
		CanSlide: True
		CruiseAltitude: 5600
		CruisingCondition: cruising
		AltitudeVelocity: 120
		TakeOffOnCreation: false
		IdleBehavior: ReturnToBase
	Hovers@CRUISING:
		RequiresCondition: cruising
	Guard:
		Voice: Attack
	Guardable:
	MustBeDestroyed:
	Targetable@ground:
		RequiresCondition: !airborne
		TargetTypes: Ground, Vehicle
	Targetable@REPAIR:
		RequiresCondition: !airborne && damaged
		TargetTypes: Repair
	GrantConditionOnDamageState@DAMAGED:
		Condition: damaged
		ValidDamageStates: Light, Medium, Heavy, Critical
	DeathSounds:
	AppearsOnRadar:
		UseLocation: true
	BodyOrientation:
		QuantizedFacings: 0
		CameraPitch: 85
		UseClassicPerspectiveFudge: false
	WithVoxelBody:
	RenderVoxels:
		Scale: 11.7
		LightYaw: 800
		LightPitch: 150
		LightAmbientColor: -0.5,-0.5,-0.5
		LightDiffuseColor: 1.4,1.4,1.4
	HiddenUnderFog:
		Type: GroundPosition
		AlwaysVisibleStances: None
	AttackMove:
	MapEditorData:
		Categories: Aircraft
	Targetable@materials:
		TargetTypes: Metel




^CommonAircraft:
	Inherits@1: ^ExistsInWorld
	OwnerLostAction:
		Action: Kill
		DeathTypes: BulletDeath
	Targetable@airborne:
		TargetTypes: Air
		RequiresCondition: airborne
	SelectionDecorations:
		Palette: pips
	Selectable:
	Aircraft:
		Voice: Move
		AirborneCondition: airborne
		CanHover: True
		VTOL: true
		CanSlide: True
		CruiseAltitude: 2560
	HiddenUnderFog:
		Type: CenterPosition
	ActorLostNotification:
	BodyOrientation:
		QuantizedFacings: 0
		CameraPitch: 85
		UseClassicPerspectiveFudge: false
	Guard:
		Voice: Attack
	Guardable:
	MustBeDestroyed:
	RenderVoxels:
		Scale: 11.7
		LightYaw: 800
		LightPitch: 150
		LightAmbientColor: -0.5,-0.5,-0.5
		LightDiffuseColor: 1.4,1.4,1.4
	Targetable@ground:
		RequiresCondition: !airborne
		TargetTypes: Ground, Vehicle
	Targetable@REPAIR:
		RequiresCondition: !airborne && damaged
		TargetTypes: Repair
	GrantConditionOnDamageState@DAMAGED:
		Condition: damaged
		ValidDamageStates: Light, Medium, Heavy, Critical
	DeathSounds:
	AppearsOnRadar:
		UseLocation: true
	MapEditorData:
		Categories: Aircraft
	EjectOnDeath:
		PilotActor: mngunner
		SuccessRate: 100
		EjectOnGround: false
		EjectInAir: true
		AllowUnsuitableCell: true
		# ChuteSound: chute1.aud
	Targetable@materials:
		TargetTypes: Metel

^CommonInfantry:
	Inherits@1: ^ExistsInWorld
	Inherits@2: ^SpriteActor
	Inherits@3: ^GainsExperience
	Inherits@4: ^ChronoDisable
	Inherits@5: ^CrateStatModifiers
	Health:
	OwnerLostAction:
		Action: Kill
		DeathTypes: BulletDeath
	HitShape:
		Type: Circle
			Radius: 128
	Armor:
		Type: None
	RevealsShroud:
		Range: 4c0
	Mobile:
		Speed: 60
		Voice: Move
		Locomotor: foot
	WithTextControlGroupDecoration:
	SelectionDecorations:
		Palette: pips
	Selectable:
	Targetable:
		TargetTypes: Ground, Infantry, DetonateAttack, Disguise
	WithInfantryBody:
		StandSequences: stand
		MoveSequence: run
		IdleSequences: idle1,idle2
		DefaultAttackSequence: shoot
	DamagedByTerrain:
		Terrain: Ore
		Damage: 2
		DamageInterval: 16
		DamageTypes: TiberiumDeath
		RequiresCondition: !hazmatsuits
	WithDeathAnimation@normal:
		DeathSequencePalette: n_mngr
		DeathTypes:
			ExplosionDeath: 2
			BulletDeath: 1
			TiberiumDeath: 3
	WithDeathAnimation@effect:
		DeathSequencePalette: n_mngr
		DeathTypes:
			RadiationDeath: 3
			PsychicDeath: 2
			ElectroDeath: 2
	SpawnActorOnDeath@flames:
		Actor: FLAMEGUY
		DeathType: FlameDeath
	TakeCover:
		SpeedModifier: 50
		ProneOffset: 443,10,100
		DamageModifiers:
			Prone50Percent: 50
			Prone70Percent: 70
			Prone100Percent: 100
		DamageTriggers: TriggerProne
	Passenger:
		Voice: Move
		CargoType: Infantry
	HiddenUnderFog:
	ActorLostNotification:
	ProximityCaptor:
		Types: Infantry
	Crushable:
		CrushClasses: infantry
		CrushSound: death_03.wav
	EdibleByLeap:
	Guard:
		Voice: Attack
	Guardable:
	DeathSounds@normal:
		DeathTypes: ExplosionDeath, BulletDeath
	DeathSounds@burned:
		Voice: Burned
		DeathTypes: FlameDeath
	DeathSounds@POISONED:
		Voice: Poisoned
		DeathTypes: TiberiumDeath
	MustBeDestroyed:
	Cloneable:
		Types: infantry
	Voiced:
		VoiceSet: GenericVoice
	QuantizeFacingsFromSequence:
		Sequence: stand
	Repairable:
		RepairActors: cahosp
		Voice: Move
	MapEditorData:
		Categories: Infantry
	Targetable@materials:
		TargetTypes: Meat



^OreDrill:
	Inherits@1: ^SpriteActor
	Tooltip:
		Name: 晶化孢子树
	WithSpriteBody:
	Building:
		Footprint: x
		Dimensions: 1,1
	AppearsOnRadar:
	RadarColorFromTerrain:
		Terrain: Ore
	BodyOrientation:
	FrozenUnderFog:
	SeedsResource:
		ResourceType: Ore
		Interval: 35
	WithIdleAnimation:
	QuantizeFacingsFromSequence:
	RenderSprites:
		Palette: player
	HitShape:
		UseTargetableCellsOffsets: true
	MapEditorData:
		Categories: Resource spawn
	Interactable:
	Targetable@materials:
		TargetTypes: Meat


^Tree:
	Inherits@1: ^ExistsInWorld
	Inherits@2: ^SpriteActor
	WithSpriteBody:
		ForceToGround: true
	FrozenUnderFog:
	Building:
		Footprint: x
		Dimensions: 1, 1
	AppearsOnRadar:
	BodyOrientation:
	Tooltip:
		Name: 树
	QuantizeFacingsFromSequence:
	RenderSprites:
		Palette: terrain
	Targetable:
		TargetTypes: Ground, DetonateAttack
	Health:
		HP: 200
	Crushable:
		CrushClasses: tree
	SoundOnDamageTransition:
		DamagedSounds: ricochet5.wav, ricochet6.wav
		DestroyedSounds: ricochet5.wav, ricochet6.wav
	HitShape:
		Type: Circle
			Radius: 256
	Armor:
		Type: Wood
	MapEditorData:
		Categories: Tree
	Interactable:
	Targetable@materials:
		TargetTypes: Concrete, Grass, Tree
	SpawnActorOnDeath:
		Actor: TREE01burnt
		DeathType: FlameDeath
	ExternalCondition@OnFire:
		Condition: KeepBurning
	DamagedByTerrain:
		Terrain: Clear, Road, Bridge, Rail, Impassable, DirtRoad, Rough, Cliff, Ore, Gems
		Damage: 3
		DamageInterval: 16
		DamageTypes: FlameDeath
		RequiresCondition: KeepBurning
	WithIdleOverlay@OnFire:
		Sequence: fire
		RequiresCondition: KeepBurning
		Palette: effect

^TreeBurnt:
	Inherits: ^Tree
	Tooltip:
		Name: 烧焦的树
	WithSpriteBody:
		Sequence: burnt
	-SpawnActorOnDeath:
	Targetable@materials:
		TargetTypes: Concrete
	-ExternalCondition@OnFire:
	-DamagedByTerrain:
	-WithIdleOverlay@OnFire:

^StreetSign:
	Inherits: ^Tree
	Tooltip:
		Name: 街道标识牌
	MapEditorData:
		Categories: Decoration
	Targetable@materials:
		TargetTypes: Metel
	-SpawnActorOnDeath:
	-ExternalCondition@OnFire:
	-DamagedByTerrain:
	-WithIdleOverlay@OnFire:

^TrafficLight:
	Inherits: ^Tree
	Tooltip:
		Name: 交通信号灯
	MapEditorData:
		Categories: Decoration
	Targetable@materials:
		TargetTypes: Metel
	-SpawnActorOnDeath:
	-ExternalCondition@OnFire:
	-DamagedByTerrain:
	-WithIdleOverlay@OnFire:

^StreetLight:
	Inherits: ^Tree
	Tooltip:
		Name: 路灯
	Armor:
		Type: steel
	Health:
		HP: 50
	MapEditorData:
		Categories: Decoration
	Targetable@materials:
		TargetTypes: Metel
	-SpawnActorOnDeath:
	-ExternalCondition@OnFire:
	-DamagedByTerrain:
	-WithIdleOverlay@OnFire:

^TelephonePole:
	Inherits: ^Tree
	Tooltip:
		Name: 电话亭
	Health:
		HP: 20
	Armor:
		Type: Concrete
	MapEditorData:
		Categories: Decoration
	Targetable@materials:
		TargetTypes: Concrete
	-SpawnActorOnDeath:
	-ExternalCondition@OnFire:
	-DamagedByTerrain:
	-WithIdleOverlay@OnFire:

^Rock:
	Inherits@1: ^SpriteActor
	WithSpriteBody:
		ForceToGround: true
	FrozenUnderFog:
	Building:
		Footprint: x
		Dimensions: 1, 1
	AppearsOnRadar:
	BodyOrientation:
	Tooltip:
		Name: 岩石
	QuantizeFacingsFromSequence:
	RenderSprites:
		Palette: terrain
	HitShape:
		UseTargetableCellsOffsets: true
	MapEditorData:
		Categories: Rock
	Interactable:
	Targetable@materials:
		TargetTypes: Stone

^Crate:
	Inherits@1: ^SpriteActor
	HiddenUnderFog:
	Tooltip:
		Name: 补给箱
		GenericName: 补给箱
	Crate:
		TerrainTypes: Clear, Rough, Road, Ore, Gems
	RenderSprites:
		Palette: player
		Image: crate
	WithCrateBody:
		LandSequence: land
		WaterSequence: water
	MapEditorData:
		Categories: System
	Interactable:
	Targetable@materials:
		TargetTypes: Concrete, Grass