###
# ^SpiritVehicle
# ^TurretedVehicle
# ^AtkFrontalVehicle
###

^SpiritVehicle:
	Inherits@1: ^ExistsInWorld
	Inherits@2: ^GainsExperience
	Inherits@3: ^IronCurtainable
	Inherits@4: ^ChronoDisable
	Inherits@5: ^CrateStatModifiers
	Inherits@6: ^ParachutableVehicle
	OwnerLostAction:
		Action: Kill
		DeathTypes: BulletDeath
	Mobile:
		Voice: Move
		TurnSpeed: 5
		Locomotor: wheeled
	SelectionDecorations:
		Palette: pips
	Selectable:
		Bounds: 32,32
	Targetable:
		TargetTypes: Ground, Vehicle, DetonateAttack
	Targetable@REPAIR:
		RequiresCondition: damaged
		TargetTypes: Repair
	GrantConditionOnDamageState@DAMAGED:
		Condition: damaged
		ValidDamageStates: Light, Medium, Heavy, Critical
	Repairable:
		Voice: Move
		RepairActors: gadept, nadept, caoutp, repairdepot
	Passenger:
		Voice: Move
		CargoType: Vehicle
		Weight: 3
	HiddenUnderFog:
	WithTextControlGroupDecoration:
	ActorLostNotification:
	ProximityCaptor:
		Types: Vehicle
	Guard:
		Voice: Attack
	Guardable:
	BodyOrientation:
		QuantizedFacings: 0
		CameraPitch: 85
		UseClassicPerspectiveFudge: false
	Explodes:
		Weapon: UnitExplodeSmall
		EmptyWeapon: UnitExplodeSmall
	# RenderVoxels:
	# 	Scale: 11.7
	# 	LightYaw: 800
	# 	LightPitch: 150
	# 	LightAmbientColor: -0.5,-0.5,-0.5
	# 	LightDiffuseColor: 1.4,1.4,1.4
	MustBeDestroyed:
	MapEditorData:
		Categories: Vehicle
	Voiced:
		VoiceSet: VehicleVoice
  WithFacingSpriteBody:
  RenderSprites:

^TurretedVehicle:
	Inherits: ^SpiritVehicle
  WithSpriteTurret:
	AttackTurreted:
		Voice: Attack
 	Turreted:
		TurnSpeed: 20
	AutoTarget:
	HitShape:

^AtkFrontalVehicle:
  Inherits: ^SpiritVehicle
	AttackFrontal:
		Voice: Attack
  AutoTarget:
	HitShape:
